### ISSUE TITLE
Here's a good resource for API creds question

### ISSUE THREAD

**Issue by thatsjet** [security-prince/Application-Security-Engineer-Interview-Questions#1]
https://medium.com/hackernoon/where-do-you-keep-credentials-for-your-lambda-functions-cac746048480

**Comment by security-prince** [comment]
Thank you :)
https://github.com/security-prince/Application-Security-Engineer-Interview-Questions/commit/7b4f93c2d6945482c37a58709783fa5c510a9aa8
